config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :comments
  resources :sessions

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    root to: 'posts#index'
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  get '/404', controller: 'application', action: 'render_404'
  get '*path', controller: 'application', action: 'render_404'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :user_id, presence: true, numericality: true
  validates :post_id, presence: true, numericality: true
  validates :content, presence: true ,length: { maximum: 512 }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments

  validates :user_id, presence: true, numericality: true
  validates :content, presence: true ,length: { maximum: 512 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/after_login_application_controller.rb
# frozen_string_literal: true

class AfterLoginApplicationController < ApplicationController
  before_action :authenticate_user!
  before_action :set_logged_in

  private
    def set_logged_in
      @user = current_user
      @user_signed_in = user_signed_in?
    end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from Exception, with: :render_404
  
  def render_404
    render template: 'errors/404', status: 404, layout: 'application', content_type: 'text/html'
  end
  
  def render_500
    render template: 'errors/500', status: 500, layout: 'application', content_type: 'text/html'
  end
end

app/controllers/comments_controller.rb
class CommentsController < AfterLoginApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    if params[:post_id] != nil then
      @post_id = params[:post_id]
    else
      raise ActionController::RoutingError
    end

    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    if params[:post_id] != nil then
      @post_id = params[:post_id]
    else
      raise ActionController::RoutingError
    end
    
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "コメントしました." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "コメントを更新しました." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "コメントを削除しました." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < AfterLoginApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @user = current_user
    @posts = Post.all.order("posts.created_at desc").includes(:comments).order("comments.created_at desc")
  end

  # GET /posts/1 or /posts/1.json
  def show
    @user = current_user
  end

  # GET /posts/new
  def new
    @user = current_user
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @user = current_user
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "ツイートしました." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @user = current_user
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "ツイートを更新しました." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    Comment.where(post_id: @post.id).destroy_all
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "ツイートを削除しました." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">

  <p>
    <strong>コメント: </strong>
    <%= comment.content %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation" style="color: red">
      <h2>コメントの投稿に失敗しました。</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :user_id, :value => @user.id %>
  <%= form.hidden_field :post_id, :value => @post_id %>

  <div>
    <%= form.label :content, "内容", style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>コメントを編集</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "コメントを表示", @comment %> |
  <%= link_to "タイムラインに戻る", posts_path %>
</div>

app/views/comments/index.html.erb
<h1>コメント</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "コメントを表示", comment %>
    </p>
  <% end %>
</div>

<%= link_to "新しいコメント", new_comment_path %>

app/views/comments/new.html.erb
<h1>新しいコメント</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "タイムラインに戻る", posts_path %>
</div>

app/views/comments/show.html.erb
<%= render @comment %>

<div>
  <%= link_to "タイムラインに戻る", posts_path %>
  <% if @user.id == @comment.user_id %>
  | <%= link_to "コメントを編集する", edit_comment_path(@comment, post_id: @comment.post_id) %>

  <%= button_to "このコメントを削除する", @comment, method: :delete %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsondocker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> %>
  </head>

  <body>
    <header>
      <% if @user_signed_in %>
        <%= button_to "ログアウト", destroy_user_session_path, method: :delete %>
      <% end %>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:article, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red" id="error_explanation">
      <h2>ツイートの投稿に失敗しました。</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, :value => @user.id %>

  <div>
    <%= form.label :content, "内容", style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <section>
    <p>
      <strong>User:</strong>
      <%= post.user_id %>
    </p>

    <p>
      <strong>ツイート内容:</strong>
      <%= post.content %>
    </p>
  <section>

  <% if post.comments %>
    <% post.comments.each do |comment| %>
      <blockquote>
        <strong>コメント:</strong>
        <%= comment.content %>
      </blockquote>
      <% if @user.id == comment.user_id %>
        <%= link_to "コメントを編集する", comment, class: 'button' %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>ツイートを編集</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "ツイートを表示", @post %> |
  <%= link_to "タイムラインに戻る", posts_path %>
</div>

app/views/posts/index.html.erb
<h1>タイムライン</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <article>
      <%= render post %>
        <%= link_to "ツイートを表示", post, class: 'button' %>
    </article>
  <% end %>
</div>

<div class="fix-spacer">
</div>
<div class="fix-bottom">
  <%= link_to "新しくツイートする", new_post_path, class: 'button' %>
</div>

app/views/posts/new.html.erb
<h1>新しい投稿</h1>
<%= render "form", post: @post %>
<br>
<div>
  <%= link_to "タイムラインに戻る", posts_path %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<div>
  <%= link_to "タイムラインに戻る", posts_path %>
  | <%= link_to "ツイートにコメントする", new_comment_path(post_id: @post.id) %>
  <% if @user.id == @post.user_id %>
    | <%= link_to "ツイートを編集する", edit_post_path(@post) %>

    <%= button_to "ツイートを削除する", @post, method: :delete %>
  <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", "/users/sign_in" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "サインアップ", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' && false %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>